//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeneralEntity2 : DbContext
    {
        public GeneralEntity2()
            : base("name=GeneralEntity2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_VCMS_roles> tbl_VCMS_roles { get; set; }
        public virtual DbSet<tbl_VCMS_userDetails> tbl_VCMS_userDetails { get; set; }
        public virtual DbSet<tbl_VCMS_users> tbl_VCMS_users { get; set; }
        public virtual DbSet<tbl_VCMS_residentBalance> tbl_VCMS_residentBalance { get; set; }
        public virtual DbSet<tbl_VCMS_residentCollection> tbl_VCMS_residentCollection { get; set; }
        public virtual DbSet<tbl_VCMS_residents> tbl_VCMS_residents { get; set; }
    
        public virtual ObjectResult<Nullable<int>> prc_VCMS_check_username(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("prc_VCMS_check_username", usernameParameter);
        }
    
        public virtual ObjectResult<prc_VCMS_get_roles_Result> prc_VCMS_get_roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_VCMS_get_roles_Result>("prc_VCMS_get_roles");
        }
    
        public virtual int prc_VCMS_register_user(string username, string password, string first_name, string last_name, Nullable<int> role_id, string email_address, string contact_number, Nullable<int> user_id_creator)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var role_idParameter = role_id.HasValue ?
                new ObjectParameter("role_id", role_id) :
                new ObjectParameter("role_id", typeof(int));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var contact_numberParameter = contact_number != null ?
                new ObjectParameter("contact_number", contact_number) :
                new ObjectParameter("contact_number", typeof(string));
    
            var user_id_creatorParameter = user_id_creator.HasValue ?
                new ObjectParameter("user_id_creator", user_id_creator) :
                new ObjectParameter("user_id_creator", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_VCMS_register_user", usernameParameter, passwordParameter, first_nameParameter, last_nameParameter, role_idParameter, email_addressParameter, contact_numberParameter, user_id_creatorParameter);
        }
    
        public virtual ObjectResult<string> prc_VCMS_get_password_hash(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("prc_VCMS_get_password_hash", usernameParameter);
        }
    
        public virtual ObjectResult<prc_VCMS_get_user_roles_and_details_Result> prc_VCMS_get_user_roles_and_details(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_VCMS_get_user_roles_and_details_Result>("prc_VCMS_get_user_roles_and_details", usernameParameter);
        }
    
        public virtual ObjectResult<prc_VCMS_get_all_users_Result> prc_VCMS_get_all_users(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_VCMS_get_all_users_Result>("prc_VCMS_get_all_users", user_idParameter);
        }
    
        public virtual ObjectResult<prc_VCMS_get_user_by_id_Result> prc_VCMS_get_user_by_id(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_VCMS_get_user_by_id_Result>("prc_VCMS_get_user_by_id", user_idParameter);
        }
    
        public virtual ObjectResult<prc_VCMS_get_all_users_search_Result> prc_VCMS_get_all_users_search(Nullable<int> user_id, string search_input)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var search_inputParameter = search_input != null ?
                new ObjectParameter("search_input", search_input) :
                new ObjectParameter("search_input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_VCMS_get_all_users_search_Result>("prc_VCMS_get_all_users_search", user_idParameter, search_inputParameter);
        }
    
        public virtual int prc_VCMS_update_user(Nullable<int> user_id, string first_name, string last_name, string email_address, string contact_number, Nullable<int> user_id_creator, Nullable<int> is_active)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var contact_numberParameter = contact_number != null ?
                new ObjectParameter("contact_number", contact_number) :
                new ObjectParameter("contact_number", typeof(string));
    
            var user_id_creatorParameter = user_id_creator.HasValue ?
                new ObjectParameter("user_id_creator", user_id_creator) :
                new ObjectParameter("user_id_creator", typeof(int));
    
            var is_activeParameter = is_active.HasValue ?
                new ObjectParameter("is_active", is_active) :
                new ObjectParameter("is_active", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_VCMS_update_user", user_idParameter, first_nameParameter, last_nameParameter, email_addressParameter, contact_numberParameter, user_id_creatorParameter, is_activeParameter);
        }
    
        public virtual ObjectResult<prc_VCMS_get_user_by_status_Result> prc_VCMS_get_user_by_status(Nullable<int> user_id, Nullable<int> status_flag)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var status_flagParameter = status_flag.HasValue ?
                new ObjectParameter("status_flag", status_flag) :
                new ObjectParameter("status_flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_VCMS_get_user_by_status_Result>("prc_VCMS_get_user_by_status", user_idParameter, status_flagParameter);
        }
    
        public virtual int prc_VCMS_create_resident(string first_name, string middle_name, string last_name, string email_address, string contact_number, string total_monthly_collection, Nullable<System.DateTime> start_of_collection, Nullable<int> has_payment, Nullable<int> user_id_creator, string payment_amount, string balance)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var contact_numberParameter = contact_number != null ?
                new ObjectParameter("contact_number", contact_number) :
                new ObjectParameter("contact_number", typeof(string));
    
            var total_monthly_collectionParameter = total_monthly_collection != null ?
                new ObjectParameter("total_monthly_collection", total_monthly_collection) :
                new ObjectParameter("total_monthly_collection", typeof(string));
    
            var start_of_collectionParameter = start_of_collection.HasValue ?
                new ObjectParameter("start_of_collection", start_of_collection) :
                new ObjectParameter("start_of_collection", typeof(System.DateTime));
    
            var has_paymentParameter = has_payment.HasValue ?
                new ObjectParameter("has_payment", has_payment) :
                new ObjectParameter("has_payment", typeof(int));
    
            var user_id_creatorParameter = user_id_creator.HasValue ?
                new ObjectParameter("user_id_creator", user_id_creator) :
                new ObjectParameter("user_id_creator", typeof(int));
    
            var payment_amountParameter = payment_amount != null ?
                new ObjectParameter("payment_amount", payment_amount) :
                new ObjectParameter("payment_amount", typeof(string));
    
            var balanceParameter = balance != null ?
                new ObjectParameter("balance", balance) :
                new ObjectParameter("balance", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_VCMS_create_resident", first_nameParameter, middle_nameParameter, last_nameParameter, email_addressParameter, contact_numberParameter, total_monthly_collectionParameter, start_of_collectionParameter, has_paymentParameter, user_id_creatorParameter, payment_amountParameter, balanceParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> prc_VCMS_check_resident(string first_name, string last_name, string email_address)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("prc_VCMS_check_resident", first_nameParameter, last_nameParameter, email_addressParameter);
        }
    }
}
