//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestoEntity : DbContext
    {
        public RestoEntity()
            : base("name=RestoEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_resto> tb_resto { get; set; }
        public virtual DbSet<tb_resto_categories> tb_resto_categories { get; set; }
        public virtual DbSet<tb_resto_items> tb_resto_items { get; set; }
    
        public virtual ObjectResult<sp_resto_get_specials_Result> sp_resto_get_specials(Nullable<int> resto_id)
        {
            var resto_idParameter = resto_id.HasValue ?
                new ObjectParameter("resto_id", resto_id) :
                new ObjectParameter("resto_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_resto_get_specials_Result>("sp_resto_get_specials", resto_idParameter);
        }
    }
}
