//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestoAdminEntity : DbContext
    {
        public RestoAdminEntity()
            : base("name=RestoAdminEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ra_roles> tb_ra_roles { get; set; }
        public virtual DbSet<tb_ra_users> tb_ra_users { get; set; }
    
        public virtual ObjectResult<sp_ra_getRoles_Result> sp_ra_getRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ra_getRoles_Result>("sp_ra_getRoles");
        }
    
        public virtual int sp_ra_registerUser(string username, string password, Nullable<int> roleId, string firstName, string middleName, string lastName, string createdBy)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("middleName", middleName) :
                new ObjectParameter("middleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ra_registerUser", usernameParameter, passwordParameter, roleIdParameter, firstNameParameter, middleNameParameter, lastNameParameter, createdByParameter);
        }
    }
}
