//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_resto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_resto()
        {
            this.tb_resto_items = new HashSet<tb_resto_items>();
        }
    
        public int id { get; set; }
        public string resto_name { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> modified_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_resto_items> tb_resto_items { get; set; }
    }
}
