//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_resto_items
    {
        public int id { get; set; }
        public int resto_id { get; set; }
        public int category_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public byte[] item_image { get; set; }
        public bool enabled { get; set; }
        public bool is_available { get; set; }
        public bool is_new { get; set; }
        public bool is_special { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> modified_by { get; set; }
    
        public virtual tb_resto tb_resto { get; set; }
        public virtual tb_resto_categories tb_resto_categories { get; set; }
    }
}
