//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_central_ws_ielts_user_details
    {
        public int ielts_user_detail_id { get; set; }
        public Nullable<int> ielts_user_id { get; set; }
        public string ielts_first_name { get; set; }
        public string ielts_middle_name { get; set; }
        public string ielts_last_name { get; set; }
        public string ielts_email_address { get; set; }
        public string ielts_contact_number { get; set; }
    
        public virtual tbl_central_ws_ielts_users tbl_central_ws_ielts_users { get; set; }
    }
}
