//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_central_ws_presmat_v2_groups
    {
        public int presmat_v2_group_id { get; set; }
        public int presmat_v2_group_no { get; set; }
        public string presmat_v2_group_name { get; set; }
        public string guid { get; set; }
    }
}
