//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VCMS_userDetails
    {
        public int user_detail_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> role_id { get; set; }
        public string email_address { get; set; }
        public string contact_number { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    
        public virtual tbl_VCMS_roles tbl_VCMS_roles { get; set; }
        public virtual tbl_VCMS_users tbl_VCMS_users { get; set; }
    }
}
