//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VCMS_residentBalance
    {
        public int balance_id { get; set; }
        public int resident_id { get; set; }
        public string balance_amount { get; set; }
        public Nullable<System.DateTime> last_payment_date { get; set; }
    
        public virtual tbl_VCMS_residents tbl_VCMS_residents { get; set; }
    }
}
