//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VCMS_residentCollection
    {
        public int collection_id { get; set; }
        public int resident_id { get; set; }
        public string payment_amount { get; set; }
        public System.DateTime date_of_payment { get; set; }
        public System.DateTime payment_month { get; set; }
    
        public virtual tbl_VCMS_residents tbl_VCMS_residents { get; set; }
    }
}
