//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_central_ws_ielts_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_central_ws_ielts_users()
        {
            this.tbl_central_ws_ielts_user_details = new HashSet<tbl_central_ws_ielts_user_details>();
        }
    
        public int ielts_user_id { get; set; }
        public string ielts_username { get; set; }
        public string ielts_password { get; set; }
        public int is_admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_central_ws_ielts_user_details> tbl_central_ws_ielts_user_details { get; set; }
    }
}
