//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_central_ws_presmat_buzzer
    {
        public int presmat_buzz_id { get; set; }
        public int presmat_group_number { get; set; }
        public int presmat_is_buzzed { get; set; }
        public Nullable<System.DateTime> presmat_date_updated { get; set; }
    }
}
