//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralRestWS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CentralWsAuthEntity : DbContext
    {
        public CentralWsAuthEntity()
            : base("name=CentralWsAuthEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_central_ws_ielts_user_details> tbl_central_ws_ielts_user_details { get; set; }
        public virtual DbSet<tbl_central_ws_ielts_users> tbl_central_ws_ielts_users { get; set; }
        public virtual DbSet<tbl_central_ws_presmat_buzzer> tbl_central_ws_presmat_buzzer { get; set; }
        public virtual DbSet<tbl_central_ws_presmat_v2_groups> tbl_central_ws_presmat_v2_groups { get; set; }
        public virtual DbSet<tbl_central_ws_presmat_group_scores> tbl_central_ws_presmat_group_scores { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Lookuptimer> Lookuptimers { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<BuzzLookup> BuzzLookups { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> ielts_insert_user(string ielts_username, string ielts_password, Nullable<int> is_admin)
        {
            var ielts_usernameParameter = ielts_username != null ?
                new ObjectParameter("ielts_username", ielts_username) :
                new ObjectParameter("ielts_username", typeof(string));
    
            var ielts_passwordParameter = ielts_password != null ?
                new ObjectParameter("ielts_password", ielts_password) :
                new ObjectParameter("ielts_password", typeof(string));
    
            var is_adminParameter = is_admin.HasValue ?
                new ObjectParameter("is_admin", is_admin) :
                new ObjectParameter("is_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ielts_insert_user", ielts_usernameParameter, ielts_passwordParameter, is_adminParameter);
        }
    
        public virtual int ielts_insert_user_details(Nullable<int> user_id, string ielts_first_name, string ielts_middle_name, string ielts_last_name, string ielts_email_address, string ielts_contact_number)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var ielts_first_nameParameter = ielts_first_name != null ?
                new ObjectParameter("ielts_first_name", ielts_first_name) :
                new ObjectParameter("ielts_first_name", typeof(string));
    
            var ielts_middle_nameParameter = ielts_middle_name != null ?
                new ObjectParameter("ielts_middle_name", ielts_middle_name) :
                new ObjectParameter("ielts_middle_name", typeof(string));
    
            var ielts_last_nameParameter = ielts_last_name != null ?
                new ObjectParameter("ielts_last_name", ielts_last_name) :
                new ObjectParameter("ielts_last_name", typeof(string));
    
            var ielts_email_addressParameter = ielts_email_address != null ?
                new ObjectParameter("ielts_email_address", ielts_email_address) :
                new ObjectParameter("ielts_email_address", typeof(string));
    
            var ielts_contact_numberParameter = ielts_contact_number != null ?
                new ObjectParameter("ielts_contact_number", ielts_contact_number) :
                new ObjectParameter("ielts_contact_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ielts_insert_user_details", user_idParameter, ielts_first_nameParameter, ielts_middle_nameParameter, ielts_last_nameParameter, ielts_email_addressParameter, ielts_contact_numberParameter);
        }
    
        public virtual ObjectResult<ielts_get_all_users_Result> ielts_get_all_users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ielts_get_all_users_Result>("ielts_get_all_users");
        }
    
        public virtual ObjectResult<Nullable<int>> presmat_get_buzzed_group()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("presmat_get_buzzed_group");
        }
    
        public virtual int presmat_new_round()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_new_round");
        }
    
        public virtual int presmat_buzz(Nullable<int> group_number)
        {
            var group_numberParameter = group_number.HasValue ?
                new ObjectParameter("group_number", group_number) :
                new ObjectParameter("group_number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_buzz", group_numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> presmat_v2_get_group_numbers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("presmat_v2_get_group_numbers");
        }
    
        public virtual int presmat_v2_register_group(Nullable<int> group_no, string group_name, string guid)
        {
            var group_noParameter = group_no.HasValue ?
                new ObjectParameter("group_no", group_no) :
                new ObjectParameter("group_no", typeof(int));
    
            var group_nameParameter = group_name != null ?
                new ObjectParameter("group_name", group_name) :
                new ObjectParameter("group_name", typeof(string));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_v2_register_group", group_noParameter, group_nameParameter, guidParameter);
        }
    
        public virtual ObjectResult<presmat_v2_get_groups_Result> presmat_v2_get_groups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<presmat_v2_get_groups_Result>("presmat_v2_get_groups");
        }
    
        public virtual int presmat_v2_logout_delete_group(Nullable<int> group_no, string guid)
        {
            var group_noParameter = group_no.HasValue ?
                new ObjectParameter("group_no", group_no) :
                new ObjectParameter("group_no", typeof(int));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_v2_logout_delete_group", group_noParameter, guidParameter);
        }
    
        public virtual ObjectResult<string> presmat_v2_get_current_time()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("presmat_v2_get_current_time");
        }
    
        public virtual int presmat_v2_insert_new_time(string time)
        {
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_v2_insert_new_time", timeParameter);
        }
    
        public virtual int presmat_v2_insert_time_to_lookup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_v2_insert_time_to_lookup");
        }
    
        public virtual ObjectResult<presmat_v2_getBuzzStartDate_EndDate_Result> presmat_v2_getBuzzStartDate_EndDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<presmat_v2_getBuzzStartDate_EndDate_Result>("presmat_v2_getBuzzStartDate_EndDate");
        }
    
        public virtual int presmat_v2_update_score(Nullable<int> group_number, Nullable<int> score)
        {
            var group_numberParameter = group_number.HasValue ?
                new ObjectParameter("group_number", group_number) :
                new ObjectParameter("group_number", typeof(int));
    
            var scoreParameter = score.HasValue ?
                new ObjectParameter("score", score) :
                new ObjectParameter("score", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("presmat_v2_update_score", group_numberParameter, scoreParameter);
        }
    
        public virtual int button_toggle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("button_toggle");
        }
    
        public virtual ObjectResult<string> check_button_enable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("check_button_enable");
        }
    }
}
